services:
    postgres:
        image: postgres:16
        container_name: invoicer_db
        restart: 'no'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB:-invoicer_db}
        ports:
            - "5432:5432"
        volumes:
            - ./db_data:/var/lib/postgresql/data

    pgweb:
        image: sosedoff/pgweb
        container_name: invoicer_pgweb
        restart: 'no'
        ports: 
            - "8008:8081" 
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-invoicer_db}?sslmode=disable
        depends_on:
            - postgres

volumes:
    db_data: